//! Tests regarding the content of the generated CHANGELOG.md

use std::process::Command;

use crate::helpers::*;

use anyhow::Result;
use assert_cmd::prelude::*;
use chrono::Utc;
use indoc::{formatdoc, indoc};
use sealed_test::prelude::*;

#[sealed_test]
fn override_default_commit() -> Result<()> {
    // Arrange
    git_init()?;

    git_add(
        indoc! {
          r#"[commit_types]
          feat = { changelog_title = "🌟 Features" }
          fix = { changelog_title = "🐛 Bug Fixes" }"#
        },
        "cog.toml",
    )?;

    let sha_init = git_commit_short("chore: init")?;
    let sha_feat = git_commit_short("feat: feature")?;
    let sha_fix = git_commit_short("fix: fix")?;

    // Act
    Command::new(assert_cmd::cargo_bin!("cog"))
        .arg("bump")
        .arg("--auto")
        .assert()
        .success();

    // Assert
    assert_tag_exists("0.1.0")?;
    assert_eq!(
        std::fs::read_to_string("CHANGELOG.md")?,
        formatdoc! {
            r#"
            # Changelog
            All notable changes to this project will be documented in this file. See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.

            - - -
            ## 0.1.0 - {today}
            #### 🌟 Features
            - feature - ({sha_feat}) - Tom
            #### 🐛 Bug Fixes
            - fix - ({sha_fix}) - Tom
            #### Miscellaneous Chores
            - init - ({sha_init}) - Tom
            
            - - -

            Changelog generated by [cocogitto](https://github.com/cocogitto/cocogitto)."#,
            today = Utc::now().naive_local().date()
        }
    );

    Ok(())
}

#[sealed_test]
fn bump_monorepo_changelog() -> Result<()> {
    // Arrange
    git_init()?;
    git_add(
        indoc!(
            r#"
            [monorepo.packages.a]
            path = "a"

            [monorepo.packages.b]
            path = "b"
            "#
        ),
        "cog.toml",
    )?;
    let init_sha = git_commit_short("chore: init")?;

    git_add("feature a", "a/file")?;
    git_commit("feat: feature a")?;

    git_add("bugfix b", "b/file")?;
    git_commit("fix: bugfix b")?;

    // Act
    Command::new(assert_cmd::cargo_bin!("cog"))
        .arg("bump")
        .arg("--auto")
        .assert()
        .success();

    // Assert
    assert_eq!(
        std::fs::read_to_string("CHANGELOG.md")?,
        formatdoc! {
            r#"
            # Changelog
            All notable changes to this project will be documented in this file. See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.

            - - -
            ## 0.1.0 - {today}
            ### Package updates
            - a bumped to a-0.1.0
            - b bumped to b-0.0.1
            ### Global changes
            #### Miscellaneous Chores
            - init - ({init_sha}) - Tom
            
            - - -

            Changelog generated by [cocogitto](https://github.com/cocogitto/cocogitto)."#,
            today = Utc::now().naive_local().date()
        }
    );

    Ok(())
}

#[sealed_test]
fn bump_monorepo_changelog_remote() -> Result<()> {
    // Arrange
    git_init()?;
    git_add(
        indoc!(
            r#"
            [monorepo.packages.a]
            path = "a"

            [monorepo.packages.b]
            path = "b"

            [changelog]
            template = "remote"
            remote = "github.com"
            owner = "cocogitto"
            repository = "cocogitto"
            "#
        ),
        "cog.toml",
    )?;
    let init_sha = git_commit("chore: init")?;
    let init_sha_short = &init_sha[..7];

    git_add("feature a", "a/file")?;
    git_commit("feat: feature a")?;

    git_add("bugfix b", "b/file")?;
    git_commit("fix: bugfix b")?;

    // Act
    Command::new(assert_cmd::cargo_bin!("cog"))
        .arg("bump")
        .arg("--auto")
        .assert()
        .success();

    // Assert
    assert_eq!(
        std::fs::read_to_string("CHANGELOG.md")?,
        formatdoc! {
            r#"
            # Changelog
            All notable changes to this project will be documented in this file. See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.

            - - -
            ## [0.1.0](https://github.com/cocogitto/cocogitto/compare/{init_sha}..0.1.0) - {today}
            ### Package updates
            - [a](a) bumped to [a-0.1.0](https://github.com/cocogitto/cocogitto/compare/{init_sha}..a-0.1.0)
            - [b](b) bumped to [b-0.0.1](https://github.com/cocogitto/cocogitto/compare/{init_sha}..b-0.0.1)
            ### Global changes
            #### Miscellaneous Chores
            - init - ([{init_sha_short}](https://github.com/cocogitto/cocogitto/commit/{init_sha})) - Tom
            
            - - -

            Changelog generated by [cocogitto](https://github.com/cocogitto/cocogitto)."#,
            today = Utc::now().naive_local().date()
        }
    );

    Ok(())
}
